spring:
  datasource:
    name: post_item
    url: jdbc:mysql://172.24.144.126/post_item
    username: uleapp_itemsrv
    password: ule.123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver